### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mikebutts** [Rennzie/jamming#3]
https://github.com/Rennzie/jamming/blob/97109dbda36c7418646db961908c93d251ebb3c8/src/components/App/App.js#L72

 I would break this out to its own function, you want to keep them doing 1 thing. Consider calling

```
  resetPlaylist() {
    this.setState({
      "playlistName": "New Playlist",
        playlistTracks: []
      }
    );
  }
```

**Comment by Rennzie** [comment]
Thank Mike, that was helpful
