### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [Rennzie/jamming#4]
Meets Expectations

Great job on this project, I had no corrections or real improvements on this because the code was solid. I really liked that the code was organized and indented properly and also commented which many do not do. I left a couple comments with suggestions but no real code improvements. It looks like you have a strong grasp of whats going on, so i would say do the capstone, add the feature in the app and then deploy this as a great portfolio piece, well done.

**Comment by Rennzie** [comment]
Thanks Mike, much appreciated. I've enjoyed the challenge and the learning!
